# Workflow's name
name: Release

permissions:
  contents: write

# Workflow's trigger
on:
  push:
    tags:
      - "v*"

# Workflow's jobs
jobs:
  # job's id
  release:
    # the type of machine to run the job on
    runs-on: ubuntu-latest

    # create steps
    steps:
      # step1: 检出整个仓库的历史记录
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # step2: set node env
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
